"""LLM-based summarization memory."""

from __future__ import annotations

import asyncio

from fim_agent.core.model.base import BaseLLM
from fim_agent.core.model.types import ChatMessage

from .base import BaseMemory

_SUMMARY_PROMPT = (
    "Summarize the key points of this conversation so far. "
    "Be concise and preserve important facts, decisions, and context."
)


class SummaryMemory(BaseMemory):
    """Memory that summarizes older messages using an LLM.

    When the stored message count exceeds *summary_threshold*, all messages
    except the most recent *keep_recent* are compressed into a single summary
    message.  The summary is stored as a system-adjacent message (role
    ``"system"``) so the agent treats it as persistent context.

    Args:
        llm: The language model used to generate summaries.
        summary_threshold: Trigger summarization when the non-system message
            count exceeds this value.
        keep_recent: Number of recent non-system messages to preserve verbatim
            after summarization.
    """

    def __init__(
        self,
        llm: BaseLLM,
        summary_threshold: int = 20,
        keep_recent: int = 6,
    ) -> None:
        self._llm = llm
        self._summary_threshold = summary_threshold
        self._keep_recent = keep_recent
        self._messages: list[ChatMessage] = []
        self._lock = asyncio.Lock()

    async def add_message(self, message: ChatMessage) -> None:
        async with self._lock:
            self._messages.append(message)

            non_system = [m for m in self._messages if m.role != "system"]
            if len(non_system) > self._summary_threshold:
                await self._summarize()

    async def get_messages(self) -> list[ChatMessage]:
        async with self._lock:
            return list(self._messages)

    async def clear(self) -> None:
        async with self._lock:
            self._messages.clear()

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    async def _summarize(self) -> None:
        """Compress older messages into a summary.

        Splits the non-system messages into two groups:

        * **old** -- everything before the last *keep_recent* messages.  These
          are replaced by a single summary message.
        * **recent** -- the most recent *keep_recent* messages, kept verbatim.

        The summary is generated by asking the LLM to condense the old
        messages.  It is stored as a ``system`` message so the agent treats it
        as persistent context alongside the original system prompt.
        """
        system_msgs = [m for m in self._messages if m.role == "system"]
        non_system = [m for m in self._messages if m.role != "system"]

        # Nothing to summarize if we have fewer messages than keep_recent.
        if len(non_system) <= self._keep_recent:
            return

        old_messages = non_system[: -self._keep_recent]
        recent_messages = non_system[-self._keep_recent :]

        # Build a transcript of the old messages for the LLM to summarize.
        transcript_lines: list[str] = []
        for msg in old_messages:
            transcript_lines.append(f"{msg.role}: {msg.content or ''}")
        transcript = "\n".join(transcript_lines)

        summary_request = [
            ChatMessage(role="system", content=_SUMMARY_PROMPT),
            ChatMessage(role="user", content=transcript),
        ]

        result = await self._llm.chat(summary_request)
        summary_text = result.message.content or ""

        summary_msg = ChatMessage(
            role="system",
            content=f"[Conversation summary]: {summary_text}",
        )

        # Rebuild: original system messages + summary + recent messages.
        self._messages = system_msgs + [summary_msg] + recent_messages
